name: ibex_knowledge_base_utilities_dev

channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandoc # install the commandline tool (pip installs a Python library that wraps it, not the tool itself)
  - pip
  - pip:
    - pandas
    - tabulate
    - bibtexparser
    - requests
    - pytest
    - black
    - flake8
    - pre-commit
    - build

